name: sqlite_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using Sqlite
version: 3.0.2
homepage: https://github.com/cachapa/sqlite_crdt
repository: https://github.com/cachapa/sqlite_crdt
issue_tracker: https://github.com/cachapa/sqlite_crdt/issues
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  sqflite_common: ^2.5.4+5
  sqflite_common_ffi: ^2.3.4
  sqflite_common_ffi_web: ^0.4.5+3
  # sql_crdt: ^3.0.2
  sql_crdt:
    git:
      url: https://github.com/Mattertorian/sql_crdt.git
      ref: deeebd6c70a2ecde1131bdc53ac43a9f02455401
#    path: ../sql_crdt

dev_dependencies:
  lints: any
  test: any
